server:
  port: 9002
  servlet:
    session:
      timeout: 600s
    context-path: /cloudalibaba-payment-service
    tomcat:
      uri-encoding: UTF-8
      max-connections: 10000
      max-http-form-post-size: 20MB

spring:
  application:
    name: nacos-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.1.107:1521/ORCL
    username: angualrdatabase
    password: angular
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
  devtools:
    livereload:
      port: 35730

management:
  endpoints:
    web:
      exposure:
        include: '*'


# mybatis-plus
mybatis-plus:
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: auto
    #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
    field-strategy: 2
    #数据库类型
    db-type: ORACLE
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    #    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    启动缓存
    cache-enabled: false
    jdbc-type-for-null: null
  type-aliases-package: com.finebo.springcloud.entity