server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//127.0.0.1:1521/ORCL
    username: angualrdatabase
    password: angular
  cloud:
    nacos:
      discovery:
        server-addr: 114.116.217.160:8848 #配置Nacos地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        #默认8719端口,假如被占用会自动从8719开始依次+1扫描，直至找到被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 114.116.217.160:8848 #nacos地址
            dataId: cloudalibaba-sentinel-service #服务名称
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  devtools:
    livereload:
      port: 35729

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true #激活Sentinel对Fegin的支持